/* =====================================================================
   Where each block is documented
   ---------------------------------------------------------------------
   Every block in the toolbox has a "Help" item in its right-click menu,
   and this is what it opens: the docs page for the category that block
   belongs to, pointed at the section that talks about the block itself
   where the docs have one.

   The table is grouped by docs page, and within a page each entry is
   `[block type, section anchor]`. It was built by reading the docs — the
   pages illustrate their blocks with screenshots named after the block
   type, so a block's section is the heading above its screenshot — and
   it is applied by blocks/lib/setHelpUrls.js.

   A block that is not listed falls back to its prefix: anything starting
   `channel_` lands on the Channels page even if it is newer than this
   table. That is why PREFIX_PAGES exists rather than only this map — a
   block added tomorrow still gets useful help.
   ===================================================================== */

import { docsUrl } from "./docs.js";

/** Block type → `page#section`, grouped by page. */
const PAGE_BLOCKS = {
  "Blocks/Apps/canvas": [
    ["canvas_asData", "sending-the-image"],
    ["canvas_clearCanvas", "drawing"],
    ["canvas_createCanvas", "creating-a-canvas"],
    ["canvas_drawCircle", "drawing"],
    ["canvas_drawImage", "drawing"],
    ["canvas_drawLine", "drawing"],
    ["canvas_drawRectangle", "drawing"],
    ["canvas_fillText", "drawing"],
    ["canvas_height", "creating-a-canvas"],
    ["canvas_restore", "transforms"],
    ["canvas_rotate", "transforms"],
    ["canvas_save", "transforms"],
    ["canvas_setFillColor", "setting-up-a-style"],
    ["canvas_setFont", "setting-up-a-style"],
    ["canvas_setLineWidth", "setting-up-a-style"],
    ["canvas_setStrokeColor", "setting-up-a-style"],
    ["canvas_strokeText", "drawing"],
    ["canvas_translate", "transforms"],
    ["canvas_width", "creating-a-canvas"],
  ],
  "Blocks/Apps/captcha": [
    ["captcha_create_mutator", "the-blocks"],
    ["captcha_value", "the-blocks"],
  ],
  "Blocks/Apps/fetch": [
    ["fetch_configSection", "an-advanced-request"],
    ["fetch_responseData", "reading-the-response"],
    ["fetch_responseHeaders", "reading-the-response"],
    ["fetch_responseStatus", "reading-the-response"],
    ["fetch_send", "a-simple-request"],
    ["fetch_sendAdvanced", "an-advanced-request"],
    ["object_getkey", "reading-the-response"],
  ],
  "Blocks/Apps/roblox": [
    ["roblox_gameInfo", "games"],
    ["roblox_getGame", "games"],
    ["roblox_getGroup", "groups"],
    ["roblox_getUser", "users"],
    ["roblox_groupInfo", "groups"],
    ["roblox_ownsBadge", "gamepasses-and-badges"],
    ["roblox_ownsGamepass", "gamepasses-and-badges"],
    ["roblox_profileLink", "quick-lookups"],
    ["roblox_userAvatar", "quick-lookups"],
    ["roblox_userGroupRank", "groups"],
    ["roblox_userId", "quick-lookups"],
    ["roblox_userInGroup", "groups"],
    ["roblox_userInfo", "users"],
  ],
  "Blocks/Apps/scratch": [
    ["scratch_getmessages", "message-count"],
    ["scratch_getprofile", "getting-a-profile"],
    ["scratch_getprofileinfo", "getting-a-profile"],
  ],
  "Blocks/Components/buttons": [
    ["buttons_add", "adding-a-button"],
    ["buttons_del", "deleting-the-reply"],
    ["buttons_event", "responding-to-a-click"],
    ["buttons_id", "responding-to-a-click"],
    ["buttons_message", "what-you-get-from-the-click"],
    ["cv2_editReplyInteraction", "slow-work-defer-first"],
    ["cv2_replyInteraction", "replying"],
    ["misc_int_channel", "what-you-get-from-the-click"],
    ["misc_int_deferReply", "slow-work-defer-first"],
    ["misc_int_member", "what-you-get-from-the-click"],
    ["misc_int_server", "what-you-get-from-the-click"],
    ["misc_int_user", "what-you-get-from-the-click"],
  ],
  "Blocks/Components/file-display": [
    ["cv2_addFile", "add-file"],
    ["cv2_file", "show-file"],
  ],
  "Blocks/Components/layout": [
    ["cv2_container", "container"],
    ["cv2_separator", "separator"],
    ["cv2_textDisplay", "text-display"],
    ["misc_addrow", "interactive-row"],
  ],
  "Blocks/Components/media": [
    ["cv2_mediaGallery", "media-gallery"],
    ["cv2_mediaGalleryItem", "image"],
  ],
  "Blocks/Components/sections": [
    ["cv2_section_button", "section-with-button"],
    ["cv2_section_thumbnail", "section-with-thumbnail"],
  ],
  "Blocks/Components/select-menus": [
    ["menus_add", "text-menus"],
    ["menus_addChannelMenu", "menus-discord-fills-in"],
    ["menus_addMentionableMenu", "menus-discord-fills-in"],
    ["menus_addRoleMenu", "menus-discord-fills-in"],
    ["menus_addUserMenu", "menus-discord-fills-in"],
    ["menus_addoption", "text-menus"],
    ["menus_del", "replying"],
    ["menus_event", "responding-to-a-selection"],
    ["menus_id", "responding-to-a-selection"],
    ["menus_update", "replying"],
    ["menus_value", "responding-to-a-selection"],
    ["misc_channelType", "menus-discord-fills-in"],
  ],
  "Blocks/Databases/simple": [
    ["db_add", "writing"],
    ["db_all", "reading"],
    ["db_clear", "writing"],
    ["db_create", "creating-a-database"],
    ["db_del", "writing"],
    ["db_get", "reading"],
    ["db_has", "reading"],
    ["db_push", "writing"],
    ["db_set", "writing"],
    ["db_sub", "writing"],
  ],
  "Blocks/Events/boosts": [
    ["events_boosts_levelDown", "when-the-boost-level-goes-down"],
    ["events_boosts_levelDown_newLevel", "when-the-boost-level-goes-down"],
    ["events_boosts_levelDown_oldLevel", "when-the-boost-level-goes-down"],
    ["events_boosts_levelDown_server", "when-the-boost-level-goes-down"],
    ["events_boosts_levelUp", "when-the-boost-level-goes-up"],
    ["events_boosts_levelUp_newLevel", "when-the-boost-level-goes-up"],
    ["events_boosts_levelUp_oldLevel", "when-the-boost-level-goes-up"],
    ["events_boosts_levelUp_server", "when-the-boost-level-goes-up"],
    ["events_boosts_serverBoosted", "when-a-member-boosts"],
    ["events_boosts_serverBoosted_member", "when-a-member-boosts"],
    ["events_boosts_serverBoosted_server", "when-a-member-boosts"],
    ["events_boosts_serverUnboosted", "when-a-member-removes-their-boost"],
    ["events_boosts_serverUnboosted_member", "when-a-member-removes-their-boost"],
    ["events_boosts_serverUnboosted_server", "when-a-member-removes-their-boost"],
  ],
  "Blocks/Events/custom": [
    ["events_custom", "the-blocks"],
    ["events_customParameter", "the-blocks"],
  ],
  "Blocks/Events/emojis-stickers": [
    ["events_emojis_changed", "emoji-events"],
    ["events_emojis_changedNewEmoji", "emoji-events"],
    ["events_emojis_changedOldEmoji", "emoji-events"],
    ["events_emojis_created", "emoji-events"],
    ["events_emojis_createdOrDeletedEmoji", "emoji-events"],
    ["events_emojis_deleted", "emoji-events"],
    ["events_stickers_changed", "sticker-events"],
    ["events_stickers_changedNewSticker", "sticker-events"],
    ["events_stickers_changedOldSticker", "sticker-events"],
    ["events_stickers_created", "sticker-events"],
    ["events_stickers_createdOrDeletedSticker", "sticker-events"],
    ["events_stickers_deleted", "sticker-events"],
  ],
  "Blocks/Events/member-actions": [
    ["events_members_addRole", "when-a-member-is-given-a-role"],
    ["events_members_addRole_member", "when-a-member-is-given-a-role"],
    ["events_members_addRole_role", "when-a-member-is-given-a-role"],
    ["events_members_nickname", "when-a-nickname-changes"],
    ["events_members_nickname_member", "when-a-nickname-changes"],
    ["events_members_nickname_newNickname", "when-a-nickname-changes"],
    ["events_members_nickname_oldNickname", "when-a-nickname-changes"],
    ["events_members_removeRole", "when-a-member-is-removed-from-a-role"],
    ["events_members_removeRole_member", "when-a-member-is-removed-from-a-role"],
    ["events_members_removeRole_role", "when-a-member-is-removed-from-a-role"],
  ],
  "Blocks/Events/message-actions": [
    ["events_message_ReactionAdd", "when-a-reaction-is-added"],
    ["events_message_ReactionAdd_count", "when-a-reaction-is-added"],
    ["events_message_ReactionAdd_emoji", "when-a-reaction-is-added"],
    ["events_message_ReactionAdd_msg", "when-a-reaction-is-added"],
    ["events_message_ReactionAdd_user", "when-a-reaction-is-added"],
    ["events_message_deleted", "when-a-message-gets-deleted"],
    ["events_message_deleted_message", "when-a-message-gets-deleted"],
    ["events_message_edited", "when-a-message-is-edited"],
    ["events_message_edited_message", "when-a-message-is-edited"],
    ["events_message_edited_newContent", "when-a-message-is-edited"],
    ["events_message_edited_oldContent", "when-a-message-is-edited"],
    ["events_message_pinned", "when-a-message-is-pinned"],
    ["events_message_pinned_message", "when-a-message-is-pinned"],
    ["events_message_reply", "when-a-message-is-replied-to"],
    ["msg_msg", "when-a-message-is-replied-to"],
  ],
  "Blocks/Events/server-actions": [
    ["events_guild_created", "when-the-bot-is-added-to-a-server"],
    ["events_guild_created_guild", "when-the-bot-is-added-to-a-server"],
    ["events_guild_deleted", "when-the-bot-is-removed-from-a-server"],
    ["events_guild_deleted_guild", "when-the-bot-is-removed-from-a-server"],
    ["events_guild_memberAdd", "when-a-member-joins"],
    ["events_guild_memberAdd_invite", "when-a-member-joins"],
    ["events_guild_memberAdd_member", "when-a-member-joins"],
    ["events_guild_memberAdd_server", "when-a-member-joins"],
    ["events_remove_guildmemberremove", "when-a-member-leaves"],
    ["events_remove_guildmemberremove_member", "when-a-member-leaves"],
    ["events_remove_guildmemberremove_server", "when-a-member-leaves"],
  ],
  "Blocks/Events/thread-actions": [
    ["events_thread_created", "when-a-thread-is-created"],
    ["events_thread_created_parent", "when-a-thread-is-created"],
    ["events_thread_created_thread", "when-a-thread-is-created"],
    ["events_thread_deleted", "when-a-thread-is-deleted"],
    ["events_thread_deleted_thread", "when-a-thread-is-deleted"],
  ],
  "Blocks/Messages/message": [
    ["cv2_editMsg", "sending-and-editing"],
    ["cv2_replyMsg", "sending-and-editing"],
    ["message_author_not_bot", "catching-a-message"],
    ["message_property", "reading-a-message"],
    ["misc_messageSent", "sending-and-editing"],
    ["msg_deleteOther", "deleting"],
    ["msg_get_reactions", "reading-reactions"],
    ["msg_getone", "getting-a-specific-message"],
    ["msg_isReply", "reading-a-message"],
    ["msg_pin", "pinning"],
    ["msg_react", "reactions"],
    ["msg_reaction_count", "reading-reactions"],
    ["msg_reaction_emoji", "reading-reactions"],
    ["msg_reaction_property", "reading-reactions"],
    ["msg_reaction_users", "reading-reactions"],
    ["msg_received", "catching-a-message"],
    ["msg_replyPing", "reading-a-message"],
    ["msg_replyTo", "reading-a-message"],
    ["msg_unpin", "pinning"],
  ],
  "Blocks/Messages/polls": [
    ["poll_choice", "creating-a-poll"],
    ["poll_create", "creating-a-poll"],
    ["poll_sendchannel", "sending-a-poll"],
    ["poll_whenvoteadded", "reacting-to-votes"],
    ["poll_whenvoteaddedvoteemoji", "reacting-to-votes"],
    ["poll_whenvoteaddedvotetext", "reacting-to-votes"],
    ["poll_whenvoteaddedvoteuser", "reacting-to-votes"],
  ],
  "Blocks/Messages/threads": [
    ["threads_addUser", "managing-a-thread"],
    ["threads_author", "reading-a-thread"],
    ["threads_authorMember", "reading-a-thread"],
    ["threads_channelCreateThread", "creating-a-thread"],
    ["threads_createdAt", "reading-a-thread"],
    ["threads_createdThread", "creating-a-thread"],
    ["threads_delete", "managing-a-thread"],
    ["threads_getThread", "finding-a-thread"],
    ["threads_getone", "finding-a-thread"],
    ["threads_id", "reading-a-thread"],
    ["threads_isStatus", "reading-a-thread"],
    ["threads_join", "managing-a-thread"],
    ["threads_lastMessage", "reading-a-thread"],
    ["threads_leave", "managing-a-thread"],
    ["threads_memberCount", "reading-a-thread"],
    ["threads_msgCreateThread", "creating-a-thread"],
    ["threads_msgHasThread", "finding-a-thread"],
    ["threads_msgInThread", "finding-a-thread"],
    ["threads_msgThread", "finding-a-thread"],
    ["threads_name", "reading-a-thread"],
    ["threads_parentChannel", "reading-a-thread"],
    ["threads_pin", "managing-a-thread"],
    ["threads_removeUser", "managing-a-thread"],
    ["threads_setArchived", "managing-a-thread"],
    ["threads_setLocked", "managing-a-thread"],
    ["threads_setName", "managing-a-thread"],
    ["threads_setSlowmode", "managing-a-thread"],
    ["threads_unpin", "managing-a-thread"],
  ],
  "Blocks/Servers/channels": [
    ["channel_awaitResponses_filterMsg", "waiting-for-a-reply"],
    ["channel_bulkdelete", "bulk-actions"],
    ["channel_channel", "getting-a-channel"],
    ["channel_clone", "creating-a-channel"],
    ["channel_create", "creating-a-channel"],
    ["channel_created", "reading-a-channel"],
    ["channel_createdChannel", "creating-a-channel"],
    ["channel_del", "changing-a-channel"],
    ["channel_deletable", "reading-a-channel"],
    ["channel_delete_permission", "permissions"],
    ["channel_fetchLastMessages", "reading-recent-messages"],
    ["channel_fetchedLastMessages", "reading-recent-messages"],
    ["channel_foreach", "getting-a-channel"],
    ["channel_getParent", "reading-a-channel"],
    ["channel_getnsfw", "reading-a-channel"],
    ["channel_getone", "getting-a-channel"],
    ["channel_getslowmode", "reading-a-channel"],
    ["channel_gettopic", "reading-a-channel"],
    ["channel_gettype", "reading-a-channel"],
    ["channel_id", "reading-a-channel"],
    ["channel_manageable", "reading-a-channel"],
    ["channel_name", "reading-a-channel"],
    ["channel_responses", "waiting-for-a-reply"],
    ["channel_setParent", "changing-a-channel"],
    ["channel_setPosition", "changing-a-channel"],
    ["channel_set_permission_v2", "permissions"],
    ["channel_setautoarchive", "changing-a-channel"],
    ["channel_setname", "changing-a-channel"],
    ["channel_setnsfw", "changing-a-channel"],
    ["channel_setslowmode", "changing-a-channel"],
    ["channel_settopic", "changing-a-channel"],
    ["channel_starttyping", "bulk-actions"],
    ["channel_syncPerms", "changing-a-channel"],
    ["channel_url", "reading-a-channel"],
    ["channel_waitForResponse", "waiting-for-a-reply"],
    ["cv2_sendMessage", "sending-a-message"],
  ],
  "Blocks/Servers/emojis": [
    ["emoji_author", "reading-an-emoji"],
    ["emoji_create", "managing-emojis"],
    ["emoji_created", "reading-an-emoji"],
    ["emoji_delete", "managing-emojis"],
    ["emoji_getallinserver", "getting-an-emoji"],
    ["emoji_getallinserver_value", "getting-an-emoji"],
    ["emoji_getemojiwith", "getting-an-emoji"],
    ["emoji_getguild", "reading-an-emoji"],
    ["emoji_getid", "reading-an-emoji"],
    ["emoji_getimageurl", "reading-an-emoji"],
    ["emoji_getname", "reading-an-emoji"],
    ["emoji_isanimated", "reading-an-emoji"],
    ["emoji_setname", "managing-emojis"],
  ],
  "Blocks/Servers/invites": [
    ["invite_author", "reading-an-invite"],
    ["invite_channel", "reading-an-invite"],
    ["invite_channel_foreach", "loops"],
    ["invite_create", "creating-and-deleting"],
    ["invite_created", "reading-an-invite"],
    ["invite_delete", "creating-and-deleting"],
    ["invite_event_var", "events"],
    ["invite_expiration", "reading-an-invite"],
    ["invite_foreach", "loops"],
    ["invite_foreach_var", "loops"],
    ["invite_get", "getting-an-invite"],
    ["invite_invitecreated", "events"],
    ["invite_invitedeleted", "events"],
    ["invite_temporary", "reading-an-invite"],
    ["invite_url", "reading-an-invite"],
    ["invite_uses", "reading-an-invite"],
  ],
  "Blocks/Servers/members": [
    ["cv2_sendDm", "direct-messages"],
    ["member_accent", "reading-a-member-or-user"],
    ["member_avatarURL", "reading-a-member-or-user"],
    ["member_ban", "moderation-actions"],
    ["member_bannable", "permission-and-safety-checks"],
    ["member_bannerURL", "reading-a-member-or-user"],
    ["member_bot", "reading-a-member-or-user"],
    ["member_color", "reading-a-member-or-user"],
    ["member_created", "reading-a-member-or-user"],
    ["member_dmChannel", "reading-a-member-or-user"],
    ["member_foreach", "getting-a-member-or-user"],
    ["member_getone", "getting-a-member-or-user"],
    ["member_getuser", "getting-a-member-or-user"],
    ["member_hasPermission", "permission-and-safety-checks"],
    ["member_id", "reading-a-member-or-user"],
    ["member_joined", "reading-a-member-or-user"],
    ["member_kick", "moderation-actions"],
    ["member_kickable", "permission-and-safety-checks"],
    ["member_member", "getting-a-member-or-user"],
    ["member_nickname", "reading-a-member-or-user"],
    ["member_removetimeout", "moderation-actions"],
    ["member_setnick", "moderation-actions"],
    ["member_status", "reading-a-member-or-user"],
    ["member_system", "reading-a-member-or-user"],
    ["member_timedout", "permission-and-safety-checks"],
    ["member_timeout", "moderation-actions"],
    ["member_unban", "moderation-actions"],
    ["member_user", "members-and-users"],
    ["member_userFlags", "reading-a-member-or-user"],
    ["member_username", "reading-a-member-or-user"],
  ],
  "Blocks/Servers/roles": [
    ["misc_permission", "creating-a-role"],
    ["roles_addToMember", "giving-and-taking-roles"],
    ["roles_create", "creating-a-role"],
    ["roles_createdAt", "reading-a-role"],
    ["roles_currentLoopMember", "loops"],
    ["roles_delete", "changing-a-role"],
    ["roles_foreach", "loops"],
    ["roles_foreachMember", "loops"],
    ["roles_foreach_role", "loops"],
    ["roles_getone", "getting-a-role"],
    ["roles_hasPermission", "reading-a-role"],
    ["roles_hasRole", "giving-and-taking-roles"],
    ["roles_hexColor", "reading-a-role"],
    ["roles_highest", "getting-a-role"],
    ["roles_id", "reading-a-role"],
    ["roles_name", "reading-a-role"],
    ["roles_position", "reading-a-role"],
    ["roles_removeFromMember", "giving-and-taking-roles"],
    ["roles_rename", "changing-a-role"],
    ["roles_setPermissions", "changing-a-role"],
  ],
  "Blocks/Servers/server": [
    ["boost_count", "boosts"],
    ["boost_level", "boosts"],
    ["boost_progressBar", "boosts"],
    ["boost_setProgressBar", "boosts"],
    ["server_afkchannel", "reading-a-server"],
    ["server_banner", "reading-a-server"],
    ["server_creationdate", "reading-a-server"],
    ["server_disableinvites", "actions"],
    ["server_dsc", "reading-a-server"],
    ["server_getall", "getting-a-server"],
    ["server_getone", "getting-a-server"],
    ["server_guild", "getting-a-server"],
    ["server_icon", "reading-a-server"],
    ["server_id", "reading-a-server"],
    ["server_leave", "actions"],
    ["server_membercount", "reading-a-server"],
    ["server_name", "reading-a-server"],
    ["server_ownerid", "reading-a-server"],
    ["server_ruleschannel", "reading-a-server"],
    ["server_systemchannel", "reading-a-server"],
    ["server_vanityurl", "reading-a-server"],
    ["server_verified", "reading-a-server"],
  ],
  "Blocks/Servers/stickers": [
    ["sticker_create", "managing-stickers"],
    ["sticker_created", "reading-a-sticker"],
    ["sticker_delete", "managing-stickers"],
    ["sticker_getallinserver", "getting-a-sticker"],
    ["sticker_getallinserver_value", "getting-a-sticker"],
    ["sticker_getguild", "reading-a-sticker"],
    ["sticker_getid", "reading-a-sticker"],
    ["sticker_getname", "reading-a-sticker"],
    ["sticker_geturl", "reading-a-sticker"],
    ["sticker_getwith", "getting-a-sticker"],
    ["sticker_setname", "managing-stickers"],
  ],
  "Blocks/Servers/webhooks": [
    ["webhooks_create", "creating-a-webhook"],
    ["webhooks_createdAt", "reading-a-webhook"],
    ["webhooks_createdWebhook", "creating-a-webhook"],
    ["webhooks_delete", "managing"],
    ["webhooks_edit", "managing"],
    ["webhooks_fetch", "getting-an-existing-webhook"],
    ["webhooks_id", "reading-a-webhook"],
    ["webhooks_name", "reading-a-webhook"],
    ["webhooks_owner", "reading-a-webhook"],
    ["webhooks_send", "sending"],
    ["webhooks_token", "reading-a-webhook"],
  ],
  "Blocks/colour": [
    ["colour_blend", "the-blocks"],
    ["colour_convert", "the-blocks"],
    ["colour_picker", "the-blocks"],
    ["colour_random", "the-blocks"],
    ["colour_rgb", "the-blocks"],
  ],
  "Blocks/comments": [
    ["comment_float", "the-blocks"],
    ["comment_multiline", "the-blocks"],
    ["comment_statement", "the-blocks"],
    ["comment_value", "the-blocks"],
  ],
  "Blocks/cooldowns": [
    ["cooldown_check", "the-easy-way"],
    ["cooldown_clear", "setting-and-clearing"],
    ["cooldown_clearAll", "setting-and-clearing"],
    ["cooldown_get", "checking-manually"],
    ["cooldown_has", "checking-manually"],
    ["cooldown_set", "setting-and-clearing"],
  ],
  "Blocks/dashboard": [
    ["dashboard_allServer", "per-server-blocks"],
    ["dashboard_allUser", "per-user-blocks"],
    ["dashboard_deleteServer", "per-server-blocks"],
    ["dashboard_deleteUser", "per-user-blocks"],
    ["dashboard_getServer", "per-server-blocks"],
    ["dashboard_getUser", "per-user-blocks"],
    ["dashboard_hasServer", "per-server-blocks"],
    ["dashboard_hasUser", "per-user-blocks"],
    ["dashboard_setServer", "per-server-blocks"],
    ["dashboard_setUser", "per-user-blocks"],
  ],
  "Blocks/files": [
    ["fs_deleteFile", "managing"],
    ["fs_readFile", "reading"],
    ["fs_readFile_data", "reading"],
    ["fs_readdir", "listing-a-folder"],
    ["fs_readdir_name", "listing-a-folder"],
    ["fs_readdir_path", "listing-a-folder"],
    ["fs_renameFile", "managing"],
    ["fs_writeFile", "writing"],
  ],
  "Blocks/functions": [
    ["procedures_defnoreturn", "to-do-something"],
    ["procedures_defreturn", "to-do-something-return"],
    ["procedures_ifreturn", "if-return"],
  ],
  "Blocks/javascript": [
    ["javascript_consoleclear", "logging-to-the-console"],
    ["javascript_consoleerror", "logging-to-the-console"],
    ["javascript_consoleinput", "logging-to-the-console"],
    ["javascript_consolelog", "logging-to-the-console"],
    ["javascript_consolewarn", "logging-to-the-console"],
    ["javascript_exit", "other-blocks"],
    ["javascript_raw", "raw-code"],
    ["javascript_raw_float", "raw-code"],
    ["javascript_raw_value", "raw-code"],
    ["javascript_trycatch", "handling-errors"],
    ["javascript_trycatch_error", "handling-errors"],
    ["javascript_trycatchfinally", "handling-errors"],
    ["javascript_typeof", "other-blocks"],
    ["javascript_wait", "waiting"],
    ["string_binary", "other-blocks"],
  ],
  "Blocks/lists": [
    ["list_filter", "searching-a-list"],
    ["list_find", "searching-a-list"],
    ["list_merge", "making-a-list"],
    ["lists_create_with", "making-a-list"],
    ["lists_getIndex", "reading-a-list"],
    ["lists_getSublist", "reading-a-list"],
    ["lists_indexOf", "reading-a-list"],
    ["lists_isEmpty", "reading-a-list"],
    ["lists_length", "reading-a-list"],
    ["lists_repeat", "making-a-list"],
    ["lists_reverse", "changing-a-list"],
    ["lists_setIndex", "changing-a-list"],
    ["lists_sort", "changing-a-list"],
    ["lists_split", "making-a-list"],
  ],
  "Blocks/logic": [
    ["controls_if", "if-do"],
    ["logic_boolean", "combining-conditions"],
    ["logic_case", "switch-statements"],
    ["logic_compare", "comparisons"],
    ["logic_default", "switch-statements"],
    ["logic_equalsExactly", "comparisons"],
    ["logic_negate", "combining-conditions"],
    ["logic_null", "combining-conditions"],
    ["logic_nullishOperator", "if-null"],
    ["logic_operation", "combining-conditions"],
    ["logic_switch", "switch-statements"],
    ["logic_ternary", "ternary"],
  ],
  "Blocks/loops": [
    ["controls_flow_statements", "break-out-of-loop"],
    ["controls_for", "count-with"],
    ["controls_forEach", "for-each-item-in-list"],
    ["controls_repeat_ext", "repeat-times"],
    ["controls_whileUntil", "repeat-while-until"],
  ],
  "Blocks/main": [
    ["main_bot", "the-bot-as-a-user"],
    ["main_botStart", "shut-down-and-start"],
    ["main_destroy", "shut-down-and-start"],
    ["main_env", "secrets"],
    ["main_numberof", "properties"],
    ["main_ping", "properties"],
    ["main_presence", "set-the-presence"],
    ["main_ready", "the-ready-event"],
    ["main_readyAt", "properties"],
  ],
  "Blocks/math": [
    ["math_arithmetic", "numbers-and-arithmetic"],
    ["math_atan2", "advanced-math"],
    ["math_constant", "advanced-math"],
    ["math_constrain", "checks-and-limits"],
    ["math_modulo", "numbers-and-arithmetic"],
    ["math_number", "numbers-and-arithmetic"],
    ["math_number_property", "checks-and-limits"],
    ["math_on_list", "working-with-lists-of-numbers"],
    ["math_random_float", "random-numbers"],
    ["math_random_int", "random-numbers"],
    ["math_round", "numbers-and-arithmetic"],
    ["math_single", "advanced-math"],
    ["math_toNumber", "numbers-and-arithmetic"],
    ["math_trig", "advanced-math"],
  ],
  "Blocks/music": [
    ["music_findLyrics", "getting-lyrics"],
    ["music_findLyrics_lyrics", "getting-lyrics"],
  ],
  "Blocks/objects": [
    ["object_addkey", "building-an-object"],
    ["object_deletekey", "changing-an-object"],
    ["object_has", "reading-an-object"],
    ["object_keys", "reading-an-object"],
    ["object_length", "reading-an-object"],
    ["object_new", "building-an-object"],
    ["object_parse", "json"],
    ["object_setkey", "changing-an-object"],
    ["object_stringify", "json"],
    ["object_values", "reading-an-object"],
  ],
  "Blocks/text": [
    ["text", "creating-text"],
    ["text_append", "changing-text"],
    ["text_changeCase", "changing-text"],
    ["text_charAt", "changing-text"],
    ["text_contains", "inspecting-text"],
    ["text_count", "inspecting-text"],
    ["text_getSubstring", "changing-text"],
    ["text_indexOf", "inspecting-text"],
    ["text_isEmpty", "inspecting-text"],
    ["text_join", "creating-text"],
    ["text_length", "inspecting-text"],
    ["text_multiline", "creating-text"],
    ["text_newline", "creating-text"],
    ["text_regexp", "regular-expressions"],
    ["text_regexp_exec", "regular-expressions"],
    ["text_regexp_match", "regular-expressions"],
    ["text_regexp_replace", "regular-expressions"],
    ["text_regexp_test", "regular-expressions"],
    ["text_repeat", "changing-text"],
    ["text_replace", "changing-text"],
    ["text_reverse", "changing-text"],
    ["text_startOrEndWith", "inspecting-text"],
    ["text_trim", "changing-text"],
  ],
  "Blocks/time": [
    ["time_between", "converting-and-comparing"],
    ["time_convert", "converting-and-comparing"],
    ["time_createdate", "getting-a-date"],
    ["time_date", "getting-a-date"],
    ["time_date_now", "getting-a-date"],
    ["time_msToString", "durations-as-text"],
    ["time_operation", "converting-and-comparing"],
    ["time_stringToMS", "durations-as-text"],
    ["time_timestampFromDate", "discord-timestamps"],
  ],
  "Interactions/contextmenu": [
    ["contextMenu_create", "registering-a-context-menu"],
    ["contextMenu_messageMenu", "what-was-clicked"],
    ["contextMenu_name", "responding"],
    ["contextMenu_received", "responding"],
    ["contextMenu_targetMessage", "what-was-clicked"],
    ["contextMenu_targetUser", "what-was-clicked"],
    ["contextMenu_userMenu", "what-was-clicked"],
    ["misc_createcontainer_global", "registering-a-context-menu"],
  ],
  "Interactions/modals": [
    ["modal_create", "showing-a-modal"],
    ["modal_get_author", "handling-the-submission"],
    ["modal_get_customId", "handling-the-submission"],
    ["modal_get_input_value", "reading-the-values"],
    ["modal_handle_interaction", "handling-the-submission"],
    ["modal_show", "showing-a-modal"],
    ["modalc_channelSelect", "the-inputs"],
    ["modalc_checkbox", "the-inputs"],
    ["modalc_checkboxGroup", "the-inputs"],
    ["modalc_choiceOption", "options"],
    ["modalc_fileUpload", "the-inputs"],
    ["modalc_getCheckbox", "reading-the-values"],
    ["modalc_getCheckboxGroup", "reading-the-values"],
    ["modalc_getRadioGroup", "reading-the-values"],
    ["modalc_getSelectedChannels", "reading-the-values"],
    ["modalc_getSelectedMembers", "reading-the-values"],
    ["modalc_getSelectedMentionables", "reading-the-values"],
    ["modalc_getSelectedRoles", "reading-the-values"],
    ["modalc_getSelectedUsers", "reading-the-values"],
    ["modalc_getStringSelectValues", "reading-the-values"],
    ["modalc_getUploadedFileUrls", "reading-the-values"],
    ["modalc_label", "building-the-form"],
    ["modalc_mentionableSelect", "the-inputs"],
    ["modalc_radioGroup", "the-inputs"],
    ["modalc_roleSelect", "the-inputs"],
    ["modalc_selectOption", "options"],
    ["modalc_stringSelect", "the-inputs"],
    ["modalc_textDisplay", "building-the-form"],
    ["modalc_textInput", "the-inputs"],
    ["modalc_userSelect", "the-inputs"],
  ],
  "Interactions/slash": [
    ["slash_addchoice", "choices"],
    ["slash_addoption", "options"],
    ["slash_addsubcommand", "subcommands"],
    ["slash_addsubcommandgroup", "subcommands"],
    ["slash_create_mutator", "registering-commands"],
    ["slash_getoption", "responding-to-a-command"],
    ["slash_name", "responding-to-a-command"],
    ["slash_received", "responding-to-a-command"],
  ],
};

/**
 * Docs page for a block type whose exact type is not in PAGE_BLOCKS.
 *
 * Block types are named `<area>_<thing>`, consistently enough that the
 * part before the first underscore says which category a block is in.
 * That covers the handful of blocks the docs have no screenshot of —
 * mutator variants, the sub-blocks of a mutator, blocks that predate a
 * page — and, more usefully, every block added after this file was
 * written.
 */
const PREFIX_PAGES = {
  boost: "Blocks/Servers/server",
  buttons: "Blocks/Components/buttons",
  canvas: "Blocks/Apps/canvas",
  captcha: "Blocks/Apps/captcha",
  channel: "Blocks/Servers/channels",
  colour: "Blocks/colour",
  comment: "Blocks/comments",
  contextMenu: "Interactions/contextmenu",
  controls: "Blocks/loops",
  cooldown: "Blocks/cooldowns",
  customEvent: "Blocks/Events/custom",
  database: "Blocks/Databases/simple",
  emoji: "Blocks/Servers/emojis",
  event: "Blocks/Events",
  fetch: "Blocks/Apps/fetch",
  file: "Blocks/files",
  files: "Blocks/files",
  fs: "Blocks/files",
  guild: "Blocks/dashboard",
  interaction: "Interactions",
  invite: "Blocks/Servers/invites",
  javascript: "Blocks/javascript",
  js: "Blocks/javascript",
  list: "Blocks/lists",
  lists: "Blocks/lists",
  logic: "Blocks/logic",
  main: "Blocks/main",
  math: "Blocks/math",
  member: "Blocks/Servers/members",
  menus: "Blocks/Components/select-menus",
  modal: "Interactions/modals",
  msg: "Blocks/Messages/message",
  music: "Blocks/music",
  object: "Blocks/objects",
  poll: "Blocks/Messages/polls",
  procedures: "Blocks/functions",
  roblox: "Blocks/Apps/roblox",
  role: "Blocks/Servers/roles",
  scratch: "Blocks/Apps/scratch",
  server: "Blocks/Servers/server",
  slash: "Interactions/slash",
  sticker: "Blocks/Servers/stickers",
  text: "Blocks/text",
  thread: "Blocks/Messages/threads",
  time: "Blocks/time",
  user: "Blocks/dashboard",
  variables: "Blocks/variables",
  webhook: "Blocks/Servers/webhooks",
};

/**
 * Blocks whose prefix points at the wrong page.
 *
 * `misc_` is the one prefix that is not an area: misc.js is where blocks
 * that belong to no single category ended up, so they have to be said
 * one by one.
 */
const EXCEPTIONS = {
  misc_addFile: "Blocks/Components/file-display",
  misc_createcontainer: "Blocks/Components/layout",
  misc_everyone: "Blocks/Components",
  misc_int_edit_mutator: "Interactions",
  misc_int_id: "Interactions",
  misc_int_reply_mutator: "Interactions",
  misc_permissionChannel: "Blocks/Servers/channels#permissions",
  misc_messageSent: "Blocks/Servers/channels#sending-a-message",
};

/** Flattened once, on first use: block type → `page#section`. */
let pages = null;

function table() {
  if (pages) return pages;

  pages = { ...EXCEPTIONS };

  for (const [page, blocks] of Object.entries(PAGE_BLOCKS))
    for (const [type, anchor] of blocks)
      if (!pages[type]) pages[type] = anchor ? `${page}#${anchor}` : page;

  return pages;
}

/**
 * The docs address for a block, or null if nothing sensible fits.
 *
 * Null rather than the docs home page on purpose: Blockly hides the
 * "Help" item on a block with no help URL, and a Help item that lands on
 * an index is worse than no Help item at all.
 *
 * @param {string} type a Blockly block type, e.g. `"channel_send"`
 * @returns {string|null}
 */
export function blockDocsUrl(type) {
  if (!type) return null;

  const exact = table()[type];
  if (exact) return docsUrl(exact);

  const prefix = PREFIX_PAGES[String(type).split("_")[0]];
  return prefix ? docsUrl(prefix) : null;
}
